# enter in S3/LeoFS settings and save as config.yaml
---
s3:
    default_bucket: caco_bucket1
    endpoint: http://localhost:8080
    tls: False
    # region: "us-west-2"
api_url: http://localhost:9999/api/fileProcessing
